- name: Downloading list of ranges from FreenetIS API
  local_action:
    module: uri
    url: "{{ freenetis_ranges_url }}"
    user: "{{ freenetis.user }}"
    password: "{{ freenetis.token }}"
  register: ranges
  run_once: true
- name: Downloading list of allowed IP addresses from FreenetIS API
  local_action:
    module: uri
    url: "{{ freenetis_allowed_url }}"
    user: "{{ freenetis.user }}"
    password: "{{ freenetis.token }}"
  register: allowed
  run_once: true
- name: Downloading list of self-cancel IP addresses from FreenetIS API
  local_action:
    module: uri
    url: "{{ freenetis_cancelable_url }}"
    user: "{{ freenetis.user }}"
    password: "{{ freenetis.token }}"
  register: cancelable
  run_once: true
- name: Set redirection URL
  set_fact:
    redirection_url: "{{ freenetis_redirection_url }}"