- name: Generating new ISC KEA DHCPv4 config
  template:
    src: "{{ dhcp4_template }}"
    dest: "{{ dhcp4_config }}"
    validate: "{{ dhcp4_validate }}"
  when: dhcp4_enabled
  become: true
  notify: Reload ISC KEA DHCPv4

- name: Generating new ISC KEA DHCPv6 config
  template:
    src: "{{ dhcp6_template }}"
    dest: "{{ dhcp6_config }}"
    validate: "{{ dhcp6_validate }}"
  when: dhcp6_enabled
  become: true
  notify: Reload ISC KEA DHCPv6
