- name: Installing HTTP redirector
  apt:
    name: "{{ http_package }}"
    state: present
  become: true
- name: Starting HTTP redirector
  service:
    name: "{{ http_unit }}"
    state: started
  become: true
- name: Enabling mod_rewrite
  apache2_module:
    name: rewrite
    ignore_configcheck: true
    force: true
  notify: HTTP redirector restart
- name: Enabling headers
  apache2_module:
    name: headers
    ignore_configcheck: true
    force: true
  notify: HTTP redirector restart
- name: Generating and testing new HTTP redirector config
  template:
    src: "{{ http_template }}"
    dest: "{{ http_config }}"
  become: true
  notify: HTTP redirector reload
- name: Enabling new HTTP redirector config
  file:
    src: "{{ http_config }}"
    dest: "{{ http_config_enabled }}"
    state: link
  become: true
  notify: HTTP redirector reload