version: "3"
services:
  controller:
    build: .
    image: unart/controller
    container_name: controller
    env_file: .env
    volumes:
      - ./env/:/controller/env/
      - ./inventory/:/controller/inventory/
      - ./artifacts/:/controller/artifacts/
