  - name: Mikrotik script download
    local_action: "shell sshpass -p {{ ansible_password }} scp -o StrictHostKeyChecking=no {{ ansible_user}}@{{ ansible_host }}:{{ inventory_hostname }}.rsc {{ script }}"
    become: true
    ignore_errors: true
  - name: Generating Mikrotik script
    local_action:
      module: template
      src: "{{ template }}"
      dest: "{{ script }}"
    become: true
    notify: Mikrotik script copy