---
- name: Load file zones/{{ item.key }}.yml
  include_vars:
    file: "zones/{{ item.key }}.yml"
    name: zone
  delegate_to: localhost
  when: item.value.type|default(type) == "master"
- name: Load data for zone {{ item.key }}
  set_fact:
    data: "{{ data | combine({item.key: zone}) }}"
  delegate_to: localhost
  when: item.value.type|default(type) == "master"