- name: Downloading DHCP subnets from FreenetIS API
  uri:
    url: "{{ freenetis_dhcp_subnets }}"
    user: "{{ freenetis_user }}"
    password: "{{ freenetis_token }}"
  register: freenetis_dhcp_subnets
  run_once: true
  delegate_to: localhost
- name: Set DHCP subnets from API response
  set_fact:
    dhcp4_subnets: "{{ freenetis_dhcp_subnets.json }}"
  run_once: true
