- name: Mikrotik script download
  shell: "sshpass -p {{ ansible_password }} scp -o StrictHostKeyChecking=no {{ ansible_user}}@{{ ansible_host }}:{{ inventory_hostname }}.rsc {{ qos_script }}"
  delegate_to: localhost
  become: true
  ignore_errors: true
- name: Generating Mikrotik script
  template:
    src: "{{ qos_template }}"
    dest: "{{ qos_script }}"
  delegate_to: localhost
  become: true
  notify: Mikrotik script copy
