- name: Downloading list of QoS classes from FreenetIS API
  uri:
    url: "{{ freenetis_qos_classes_url }}"
    user: "{{ freenetis_user }}"
    password: "{{ freenetis_token }}"
  delegate_to: localhost
  register: freenetis_qos_classes
- name: Setting QoS classes from FreenetIS response
  set_fact:
    qos_classes: "{{ freenetis_qos_classes.json }}"
