- name: Mikrotik script copy
  shell: "sshpass -p {{ ansible_password }} scp -o StrictHostKeyChecking=no {{ qos_script }} {{ ansible_user}}@{{ ansible_host }}:{{ inventory_hostname }}.rsc"
  become: true
  delegate_to: localhost
  notify: Mikrotik script run
- name: Mikrotik script run
  shell: "sshpass -p {{ ansible_password }} ssh -o StrictHostKeyChecking=no {{ ansible_user}}@{{ ansible_host }} /import {{ inventory_hostname }}.rsc"
  become: true
  delegate_to: localhost
