network_template: network.j2
network_json: /opt/libreqos/src/network.json
shaped_devices_template: ShapedDevices.j2
shaped_devices_csv: /opt/libreqos/src/ShapedDevices.csv
scheduler_unit: lqos_scheduler