  - name: Mikrotik script copy
    local_action: "shell sshpass -p {{ ansible_password }} scp -o StrictHostKeyChecking=no {{ script }} {{ ansible_user}}@{{ ansible_host }}:{{ inventory_hostname }}.rsc"
    become: true
    notify: Mikrotik script run
  - name: Mikrotik script run
    local_action: "shell sshpass -p {{ ansible_password }} ssh -o StrictHostKeyChecking=no {{ ansible_user}}@{{ ansible_host }} /import {{ inventory_hostname }}.rsc"
    become: true