---
- hosts: dhcp
  name: dhcp
  gather_facts: false
  tasks:
    - name: FreeNetis DHCP
      include_role:
        name: dhcp/freenetis
      when: freenetis is defined
    - name: Load DHCP driver
      include_role:
        name: "dhcp/{{ driver }}"