dhcp4_enabled: true
dhcp4_unit: isc-kea-dhcp4-server
dhcp4_template: kea-dhcp4.j2
dhcp4_config: /etc/kea/kea-dhcp4.conf
dhcp4_validate: kea-dhcp4 -t %s
dhcp4_interfaces:
  - "*"
dhcp4_socket: kea4-ctrl-socket
dhcp4_hooks: []

dhcp6_enabled: false
dhcp6_unit: isc-kea-dhcp6-server
dhcp6_template: kea-dhcp6.j2
dhcp6_config: /etc/kea/kea-dhcp6.conf
dhcp6_validate: kea-dhcp6 -t %s
dhcp6_interfaces:
  - "*"
dhcp6_socket: kea6-ctrl-socket
dhcp6_hooks: []
