dhcp_package: isc-kea-dhcp4-server
dhcp_unit: isc-kea-dhcp4-server
dhcp_template: kea-dhcp4.j2
dhcp_config: /etc/kea/kea-dhcp4.conf
dhcp_validate: kea-dhcp4 -t %s
dhcp_apt_key: https://dl.cloudsmith.io/public/isc/kea-2-2/gpg.A8CB727C62565FF8.key
dhcp_apt_repo: "deb https://dl.cloudsmith.io/public/isc/kea-2-2/deb/debian {{ ansible_distribution_release }} main"
dhcp_interfaces:
  - "*"
